# Generated by Django 3.1.14 on 2022-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='paid_account',
            field=models.BooleanField(default=False),
        ),
    ]
