# Generated by Django 3.1.14 on 2022-08-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0002_advuser_paid_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBackTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50, verbose_name='Strategy.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Test data.')),
                ('parts', models.IntegerField(verbose_name='Pairs part')),
                ('minimal_roi1_time', models.IntegerField()),
                ('minimal_roi1_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minimal_roi2_time', models.IntegerField()),
                ('minimal_roi2_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minimal_roi3_time', models.IntegerField()),
                ('minimal_roi3_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minimal_roi4_time', models.IntegerField()),
                ('minimal_roi4_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('arg_N', models.IntegerField(verbose_name='Series length (N)')),
                ('arg_R', models.IntegerField(verbose_name='Persen of same candles (R)')),
                ('arg_P', models.IntegerField(verbose_name='Price incriase in N candles (P)')),
                ('arg_MR', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Movement ROI (MR)')),
                ('stoploss', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Stop-loss (after 0 min)')),
                ('my_stoploss_time', models.IntegerField(verbose_name='My Stop-loss (after [n] min)')),
                ('my_stoploss_value', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='My Stop-loss (after [n] min)')),
                ('arg_stoploss', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Dsired Stop-loss value (S)')),
                ('text_log', models.TextField(verbose_name='Loggin text')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Test owner.')),
            ],
            options={
                'verbose_name': 'BackTest settings',
                'verbose_name_plural': 'BackTest settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
